### PR TITLE
Refactor and remove non-used sections.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
The "Potential issues" section is the only one that appears to be the only one left, if I'm not mistaken.

**Comment by ghost** [comment]
@tusooa , could you please sign off the changes and squash the commits?

**Comment by ghost** [comment]
wow, thanks, that was fast.

**Comment by ghost** [comment]
oops, @tusooa , I think I selected the wrong branch, it should have been merged to obfuscated-events not main. Sorry for the inconvenience.

**Comment by tusooa** [comment]
uh, ok.

**Comment by ghost** [comment]
should we revert the pr?

**Comment by tusooa** [comment]
i don't care, i guess i'm not gonna touch main branch

**Comment by ghost** [comment]
@tusooa do I reopen another PR into the correct branch?

**Comment by tusooa** [comment]
i'd be grateful if you do

**Pull request merged**
